AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Open3Words API - Serverless deployment on AWS Lambda

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.11
    Environment:
      Variables:
        REDIS_URL: ""
        DEFAULT_GRID: "default"
        DEFAULT_LANG: "en"

Resources:
  Open3WordsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: deploy/lambda_handler.handler
      CodeUri: .
      Description: Open3Words API
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
