"""
Wordlist Generator for Open3Words
Creates and manages a curated wordlist for the 3-word location system.
Target: 40,000 words for full global coverage at ~3m precision.
"""

import json
import re
import os
from typing import List, Set

# Comprehensive base wordlist - common, easy-to-pronounce English words
# In production, source from frequency-ranked corpora (e.g., Google Ngrams, SUBTLEX-US)
BASE_WORDS = [
    # Category 1: Very common short words (for populated urban areas)
    "act", "add", "age", "ago", "aid", "aim", "air", "all", "and", "ant",
    "any", "ape", "arc", "are", "ark", "arm", "art", "ash", "ask", "ate",
    "awl", "axe", "bad", "bag", "ban", "bar", "bat", "bay", "bed", "bee",
    "bet", "bid", "big", "bin", "bit", "bog", "bow", "box", "boy", "bud",
    "bug", "bun", "bus", "but", "buy", "cab", "cam", "can", "cap", "car",
    "cat", "cop", "cow", "cry", "cub", "cup", "cur", "cut", "dam", "day",
    "den", "dew", "did", "dig", "dim", "dip", "dog", "dot", "dry", "dub",
    "dud", "due", "dug", "dun", "duo", "dye", "ear", "eat", "eel", "egg",
    "elk", "elm", "emu", "end", "era", "eve", "ewe", "eye", "fan", "far",
    "fat", "fax", "fed", "fee", "few", "fig", "fin", "fir", "fit", "fix",
    "fly", "fog", "for", "fox", "fry", "fun", "fur", "gag", "gap", "gas",
    "gem", "get", "gin", "got", "gum", "gun", "gut", "guy", "gym", "had",
    "ham", "has", "hat", "hay", "hen", "her", "hew", "hid", "him", "hip",
    "his", "hit", "hob", "hog", "hop", "hot", "how", "hub", "hue", "hug",
    "hum", "hut", "ice", "icy", "ill", "imp", "ink", "inn", "ion", "ire",
    "irk", "its", "ivy", "jab", "jag", "jam", "jar", "jaw", "jay", "jet",
    "jig", "job", "jog", "joy", "jug", "jut", "keg", "ken", "key", "kid",
    "kin", "kit", "lab", "lad", "lag", "lap", "law", "lay", "lea", "led",
    "leg", "let", "lid", "lip", "lit", "log", "lot", "low", "lug", "mad",
    "man", "map", "mar", "mat", "maw", "may", "men", "met", "mid", "mix",
    "mob", "mod", "mop", "mow", "mud", "mug", "nab", "nag", "nap", "net",
    "new", "nil", "nip", "nit", "nod", "nor", "not", "now", "nun", "nut",
    "oak", "oar", "oat", "odd", "ode", "off", "oft", "oil", "old", "one",
    "opt", "orb", "ore", "our", "out", "owe", "owl", "own", "pad", "pal",
    "pan", "pap", "par", "pat", "paw", "pay", "pea", "peg", "pen", "pep",
    "per", "pet", "pie", "pig", "pin", "pit", "ply", "pod", "pop", "pot",
    "pow", "pro", "pry", "pub", "pug", "pun", "pup", "pus", "put", "rag",
    "ram", "ran", "rap", "rat", "raw", "ray", "red", "ref", "rep", "rib",
    "rid", "rig", "rim", "rip", "rob", "rod", "roe", "rot", "row", "rub",
    "rug", "rum", "run", "rut", "rye", "sac", "sad", "sag", "sap", "sat",
    "saw", "say", "sea", "set", "sew", "shy", "sin", "sip", "sir", "sis",
    "sit", "six", "ski", "sky", "sly", "sob", "sod", "son", "sop", "sot",
    "sow", "soy", "spa", "spy", "sty", "sub", "sue", "sum", "sun", "sup",
    "tab", "tad", "tag", "tan", "tap", "tar", "tax", "tea", "ten", "the",
    "thy", "tic", "tie", "tin", "tip", "toe", "ton", "too", "top", "tot",
    "tow", "toy", "try", "tub", "tug", "two", "urn", "use", "van", "vat",
    "vet", "vex", "via", "vie", "vim", "vow", "wad", "wag", "war", "was",
    "wax", "way", "web", "wed", "wet", "who", "why", "wig", "win", "wit",
    "woe", "wok", "won", "woo", "wow", "yak", "yam", "yap", "yaw", "yea",
    "yes", "yet", "yew", "yip", "you", "zap", "zed", "zen", "zig", "zip",
    "zoo",

    # Category 2: Common 4-letter words
    "able", "also", "arch", "area", "army", "away", "back", "bake", "ball",
    "band", "bank", "barn", "base", "bath", "bead", "beam", "bean", "bear",
    "beat", "beef", "been", "beer", "bell", "belt", "bend", "best", "bike",
    "bill", "bind", "bird", "bite", "blow", "blue", "blur", "boat", "body",
    "bold", "bolt", "bomb", "bond", "bone", "book", "boot", "born", "boss",
    "both", "bowl", "brim", "bulk", "bull", "bump", "burn", "bush", "busy",
    "buzz", "cafe", "cage", "cake", "calf", "call", "calm", "came", "camp",
    "cape", "card", "care", "cart", "case", "cash", "cast", "cave", "cell",
    "chef", "chip", "chop", "city", "clad", "clam", "clan", "clap", "clay",
    "clip", "clod", "clog", "club", "clue", "coal", "coat", "code", "coil",
    "coin", "cold", "colt", "comb", "come", "cook", "cool", "cope", "copy",
    "cord", "core", "cork", "corn", "cost", "cozy", "crab", "crew", "crop",
    "crow", "cube", "cult", "curb", "cure", "curl", "daft", "dale", "dame",
    "damp", "dare", "dark", "dart", "dash", "data", "date", "dawn", "deal",
    "dean", "dear", "deck", "deed", "deem", "deep", "deer", "deny", "desk",
    "dial", "dice", "dime", "dine", "dire", "dirt", "disc", "dish", "dock",
    "does", "dome", "done", "doom", "door", "dose", "dove", "down", "drag",
    "draw", "drip", "drop", "drum", "dual", "duck", "duel", "duke", "dull",
    "dump", "dune", "dusk", "dust", "duty", "each", "earl", "earn", "ease",
    "east", "easy", "echo", "edge", "edit", "else", "emit", "epic", "even",
    "ever", "evil", "exam", "exit", "face", "fact", "fade", "fail", "fair",
    "fake", "fall", "fame", "fang", "fare", "farm", "fast", "fate", "fawn",
    "fear", "feat", "feed", "feel", "fell", "felt", "fern", "file", "fill",
    "film", "find", "fine", "fire", "firm", "fish", "fist", "five", "flag",
    "flak", "flap", "flat", "flaw", "flea", "fled", "flex", "flip", "flit",
    "flog", "flow", "foam", "fold", "folk", "fond", "font", "food", "fool",
    "foot", "ford", "fore", "fork", "form", "fort", "foul", "four", "free",
    "frog", "from", "fuel", "full", "fume", "fund", "fuse", "fury", "fuzz",
    "gain", "gait", "gale", "game", "gang", "gape", "garb", "gash", "gasp",
    "gate", "gave", "gaze", "gear", "germ", "gift", "gild", "gill", "girl",
    "give", "glad", "glee", "glen", "glib", "glow", "glue", "glum", "glut",
    "gnat", "gnaw", "goal", "goat", "goes", "gold", "golf", "gone", "good",
    "gore", "grab", "gray", "grew", "grid", "grim", "grin", "grip", "grit",
    "grow", "grub", "gulf", "gust", "guts", "hack", "hail", "hair", "hale",
    "half", "hall", "halt", "hand", "hang", "hare", "hark", "harm", "harp",
    "hash", "hasp", "haste", "haul", "have", "hawk", "haze", "hazy", "head",
    "heal", "heap", "hear", "heat", "heed", "heel", "held", "help", "hemp",
    "herb", "herd", "here", "hero", "hide", "high", "hike", "hill", "hilt",
    "hind", "hint", "hire", "hiss", "hive", "hoax", "hold", "hole", "holy",
    "home", "hone", "hood", "hook", "hoop", "hope", "horn", "hose", "host",
    "hour", "howl", "huff", "huge", "hull", "hump", "hung", "hunt", "hurl",
    "hurt", "hush", "hymn", "icon", "idea", "idle", "inch", "info", "into",
    "iron", "isle", "item", "jack", "jade", "jail", "jazz", "jean", "jeer",
    "jerk", "jest", "jilt", "join", "joke", "jolt", "jump", "June", "jury",
    "just", "keen", "keep", "kelp", "kent", "kept", "kick", "kill", "kind",
    "king", "kiss", "kite", "knack", "knee", "knew", "knit", "knob", "knot",
    "know", "lace", "lack", "lady", "laid", "lake", "lamb", "lame", "lamp",
    "land", "lane", "lard", "lark", "lash", "lass", "last", "late", "lawn",
    "lead", "leaf", "leak", "lean", "leap", "left", "lend", "lens", "less",
    "liar", "lick", "life", "lift", "like", "lily", "limb", "lime", "limp",
    "line", "link", "lion", "list", "live", "load", "loaf", "loan", "lock",
    "loft", "lone", "long", "look", "loop", "lord", "lore", "lose", "loss",
    "lost", "loud", "love", "luck", "lull", "lump", "lung", "lure", "lurk",
    "lush", "lust", "lynx", "mace", "made", "maid", "mail", "main", "make",
    "male", "mall", "malt", "mane", "many", "mare", "mark", "mash", "mask",
    "mass", "mast", "mate", "maze", "mead", "meal", "mean", "meat", "meld",
    "melt", "memo", "mend", "menu", "mere", "mesh", "mild", "mile", "milk",
    "mill", "mime", "mind", "mine", "mint", "miss", "mist", "moan", "moat",
    "mock", "mode", "mold", "mole", "molt", "monk", "mood", "moon", "moor",
    "more", "moss", "most", "moth", "move", "much", "mule", "mull", "muse",
    "mush", "must", "mute", "myth", "nail", "name", "nave", "navy", "near",
    "neat", "neck", "need", "nest", "next", "nice", "nine", "node", "none",
    "noon", "norm", "nose", "note", "noun", "nude", "oath", "obey", "odds",
    "odor", "omen", "omit", "once", "only", "onto", "open", "oral", "orca",
    "oven", "over", "pace", "pack", "page", "paid", "pail", "pain", "pair",
    "pale", "palm", "pane", "park", "part", "pass", "past", "path", "pave",
    "peak", "pear", "peat", "peck", "peel", "peer", "pelt", "perk", "pest",
    "pick", "pier", "pike", "pile", "pine", "pink", "pipe", "plan", "play",
    "plea", "plod", "plot", "plow", "ploy", "plug", "plum", "plus", "poke",
    "pole", "poll", "polo", "pomp", "pond", "pony", "pool", "poor", "pope",
    "pore", "pork", "port", "pose", "post", "pour", "pout", "pray", "prey",
    "prod", "prop", "pull", "pulp", "pump", "punk", "pure", "push", "quad",
    "quit", "quiz", "race", "rack", "raft", "rage", "raid", "rail", "rain",
    "rake", "ramp", "rand", "rang", "rank", "rant", "rare", "rash", "rasp",
    "rate", "rave", "raze", "read", "real", "ream", "reap", "rear", "reed",
    "reef", "reel", "rein", "rely", "rent", "rest", "rice", "rich", "ride",
    "rift", "rind", "ring", "riot", "rise", "risk", "road", "roam", "roar",
    "robe", "rock", "rode", "role", "roll", "roof", "room", "root", "rope",
    "rose", "rote", "rout", "rude", "ruin", "rule", "rung", "rush", "rust",
    "sack", "safe", "saga", "sage", "said", "sail", "sake", "sale", "salt",
    "same", "sand", "sane", "sang", "sank", "sash", "save", "seal", "seam",
    "seed", "seek", "seem", "seen", "self", "sell", "send", "sent", "shed",
    "shin", "ship", "shoe", "shoo", "shop", "shot", "show", "shut", "sick",
    "side", "sift", "sigh", "sign", "silk", "sill", "silo", "silt", "sing",
    "sink", "site", "size", "slab", "slag", "slam", "slap", "slaw", "sled",
    "slew", "slid", "slim", "slip", "slit", "slob", "slop", "slot", "slow",
    "slug", "slum", "slur", "smog", "snap", "snip", "snob", "snow", "snub",
    "snug", "soak", "soap", "soar", "sock", "soda", "sofa", "soft", "soil",
    "sold", "sole", "some", "song", "soon", "soot", "sore", "sort", "soul",
    "sour", "span", "spar", "spec", "sped", "spin", "spit", "spot", "spur",
    "stab", "stag", "star", "stay", "stem", "step", "stew", "stir", "stop",
    "stub", "stud", "stun", "such", "suit", "sulk", "sung", "sunk", "sure",
    "surf", "swan", "swap", "sway", "swim", "swot", "swum", "sync", "tack",
    "tail", "take", "tale", "talk", "tall", "tame", "tank", "tape", "tarp",
    "task", "team", "tear", "teem", "tell", "temp", "tend", "tent", "term",
    "test", "text", "that", "them", "then", "they", "thin", "this", "thorn",
    "tick", "tide", "tidy", "tier", "tile", "till", "tilt", "time", "tint",
    "tiny", "tire", "toad", "toil", "told", "toll", "tomb", "tone", "took",
    "tool", "toot", "tops", "tore", "torn", "toss", "tour", "town", "trap",
    "tray", "tree", "trek", "trim", "trio", "trip", "trod", "trot", "true",
    "tuck", "tuft", "tune", "turf", "turn", "tusk", "tuft", "twin", "type",
    "ugly", "undo", "unit", "unto", "upon", "urge", "used", "user", "urea",
    "vain", "vale", "vane", "vary", "vase", "vast", "veil", "vein", "vend",
    "vent", "verb", "very", "vest", "view", "vine", "visa", "void", "volt",
    "vote", "wade", "wage", "wail", "wait", "wake", "walk", "wall", "wand",
    "want", "ward", "warm", "warn", "warp", "wart", "wash", "wasp", "wave",
    "wavy", "waxy", "weak", "wear", "weed", "week", "weep", "weld", "well",
    "went", "were", "west", "what", "when", "whim", "whip", "whom", "wick",
    "wide", "wife", "wild", "will", "wilt", "wily", "wimp", "wind", "wine",
    "wing", "wink", "wipe", "wire", "wise", "wish", "wisp", "with", "woke",
    "wolf", "wood", "wool", "word", "wore", "work", "worm", "worn", "wove",
    "wrap", "wren", "writ", "yard", "yarn", "year", "yell", "yoga", "yoke",
    "your", "zeal", "zero", "zinc", "zone", "zoom",

    # Category 3: Common 5-6 letter words
    "about", "above", "abuse", "ache", "acre", "adapt", "admit", "adopt",
    "adult", "after", "again", "agent", "agile", "agree", "alarm", "album",
    "alert", "alien", "align", "alive", "alley", "allow", "alloy", "alone",
    "along", "alpha", "alter", "amber", "amend", "ample", "angel", "anger",
    "angle", "angry", "ankle", "annex", "anvil", "apart", "apple", "apply",
    "arena", "argue", "arise", "armor", "aroma", "array", "arrow", "asset",
    "atlas", "attic", "audio", "audit", "avoid", "awake", "award", "aware",
    "awful", "badge", "badly", "baker", "banjo", "baron", "basin", "basis",
    "batch", "beach", "beard", "beast", "began", "begin", "being", "below",
    "bench", "berry", "birth", "black", "blade", "blame", "blank", "blast",
    "blaze", "bleak", "bleed", "blend", "bless", "blind", "blink", "bliss",
    "block", "blond", "blood", "bloom", "blown", "board", "boast", "bonus",
    "boost", "booth", "bound", "brain", "brand", "brave", "bread", "break",
    "breed", "brick", "bride", "brief", "bring", "broad", "broke", "brook",
    "broom", "broth", "brown", "brush", "buddy", "build", "built", "bunch",
    "burnt", "burst", "buyer", "cabin", "cable", "camel", "candy", "cargo",
    "carry", "catch", "cause", "cedar", "chain", "chair", "chalk", "champ",
    "charm", "chart", "chase", "cheap", "check", "cheek", "cheer", "chess",
    "chest", "child", "chill", "china", "choir", "chose", "chunk", "civic",
    "claim", "clash", "clasp", "class", "clean", "clear", "clerk", "cliff",
    "climb", "cling", "clock", "clone", "close", "cloth", "cloud", "clown",
    "coach", "coast", "color", "comet", "coral", "count", "court", "cover",
    "crack", "craft", "crane", "crash", "crawl", "crazy", "cream", "creek",
    "crest", "crime", "crisp", "cross", "crowd", "crown", "crude", "crush",
    "curve", "cycle", "daddy", "daily", "dairy", "dance", "debut", "decay",
    "delta", "demon", "dense", "depth", "derby", "deter", "devil", "diary",
    "dicey", "digit", "ditch", "dizzy", "dodge", "donor", "doubt", "dough",
    "draft", "drain", "drake", "drape", "drawn", "dread", "dream", "dress",
    "dried", "drift", "drill", "drink", "drive", "droit", "drone", "drove",
    "drown", "drunk", "dryer", "dusty", "dwarf", "dwell", "eager", "eagle",
    "early", "earth", "eight", "elbow", "elder", "elect", "elite", "embed",
    "ember", "empty", "endow", "enemy", "enjoy", "enter", "entry", "equal",
    "equip", "erect", "error", "essay", "event", "every", "exact", "exile",
    "exist", "extra", "fable", "facet", "fairy", "faith", "false", "fancy",
    "feast", "fence", "ferry", "fetch", "fever", "fiber", "field", "fiery",
    "fifty", "fight", "final", "first", "fixed", "flame", "flank", "flare",
    "flash", "flask", "fleet", "flesh", "flick", "fling", "flint", "float",
    "flock", "flood", "floor", "flora", "flour", "flowy", "fluid", "fluke",
    "flush", "flute", "focus", "foggy", "force", "forge", "forth", "forum",
    "found", "frame", "frank", "fraud", "freek", "fresh", "friar", "fried",
    "front", "frost", "froze", "fruit", "fully", "funny", "fuzzy", "gauge",
    "ghost", "giant", "given", "glare", "glass", "gleam", "globe", "gloom",
    "glory", "gloss", "glove", "going", "goose", "gorge", "grace", "grade",
    "grain", "grand", "grant", "grape", "graph", "grasp", "grass", "grate",
    "grave", "graze", "great", "greed", "green", "greet", "grief", "grill",
    "grind", "groan", "groom", "gross", "group", "grove", "growl", "grown",
    "guard", "guess", "guest", "guide", "guild", "guilt", "guise", "gulch",
    "gully", "gusto", "habit", "happy", "hardy", "harsh", "haste", "haven",
    "heart", "heavy", "hedge", "hefty", "hello", "hence", "heron", "hilly",
    "hinge", "hippo", "hobby", "holes", "holly", "honey", "honor", "horse",
    "hotel", "house", "human", "humid", "humor", "ideal", "image", "imply",
    "index", "indie", "infer", "inner", "input", "irate", "ivory", "jolly",
    "judge", "juice", "juicy", "jumbo", "kayak", "knock", "known", "label",
    "labor", "laser", "latch", "later", "layer", "learn", "lease", "leave",
    "ledge", "legal", "lemon", "level", "lever", "light", "linen", "liver",
    "llama", "local", "lodge", "logic", "loose", "lotus", "lover", "lower",
    "lucky", "lunar", "lunch", "magic", "major", "maker", "manor", "maple",
    "march", "match", "mayor", "melon", "mercy", "merge", "merit", "merry",
    "metal", "meter", "might", "miner", "minor", "minus", "model", "money",
    "month", "moral", "mount", "mourn", "mouth", "movie", "muddy", "music",
    "naive", "named", "nasty", "naval", "nerve", "never", "next", "night",
    "noble", "noise", "north", "notch", "noted", "novel", "nurse", "nylon",
    "occur", "ocean", "offer", "often", "olive", "onset", "opera", "orbit",
    "order", "organ", "other", "outer", "owned", "owner", "oxide", "ozone",
    "paint", "panel", "panic", "paper", "party", "pasta", "paste", "patch",
    "pause", "peace", "peach", "pearl", "pedal", "penny", "perch", "phase",
    "phone", "photo", "piano", "piece", "pilot", "pinch", "pitch", "pixel",
    "pizza", "place", "plaid", "plain", "plane", "plank", "plant", "plate",
    "plaza", "plead", "pleat", "plier", "pluck", "plumb", "plume", "plump",
    "plush", "poach", "point", "polar", "posed", "posse", "pouch", "pound",
    "power", "press", "price", "pride", "prime", "print", "prior", "prize",
    "probe", "prone", "proof", "prose", "proud", "prove", "prune", "pulse",
    "punch", "pupil", "purse", "queen", "query", "quest", "queue", "quick",
    "quiet", "quilt", "quite", "quota", "quote", "radar", "radio", "rally",
    "ranch", "range", "rapid", "ratio", "razor", "reach", "react", "ready",
    "realm", "rebel", "reign", "relax", "relay", "ridge", "rifle", "rigid",
    "ripen", "risen", "risky", "rival", "river", "roast", "robin", "robot",
    "rocky", "rogue", "roman", "roost", "rouge", "rough", "round", "route",
    "royal", "rugby", "ruler", "rural", "rusty", "salad", "salon", "salty",
    "sandy", "sauce", "sauna", "scale", "scare", "scarf", "scene", "scent",
    "scope", "score", "scout", "scrap", "shaft", "shake", "shall", "shame",
    "shape", "share", "shark", "sharp", "shawl", "shear", "sheep", "sheer",
    "sheet", "shelf", "shell", "shift", "shine", "shirt", "shock", "shore",
    "short", "shout", "shove", "shown", "shrub", "siege", "sight", "sigma",
    "since", "siren", "sixth", "sixty", "skate", "skill", "skull", "slash",
    "slate", "slave", "sleep", "sleek", "slice", "slide", "slope", "smart",
    "smell", "smile", "smith", "smoke", "snack", "snake", "solar", "solid",
    "solve", "sonic", "sorry", "sound", "south", "space", "spare", "spark",
    "speak", "spear", "speed", "spell", "spend", "spice", "spike", "spine",
    "spoke", "spoon", "sport", "spray", "squid", "staff", "stage", "stain",
    "stair", "stake", "stale", "stalk", "stall", "stamp", "stand", "stank",
    "stare", "stark", "start", "state", "stays", "steak", "steal", "steam",
    "steel", "steep", "steer", "stern", "stick", "stiff", "still", "sting",
    "stink", "stock", "stoke", "stole", "stone", "stood", "stool", "store",
    "storm", "story", "stout", "stove", "strap", "straw", "stray", "strip",
    "stuck", "stuff", "stump", "stung", "stunk", "style", "sugar", "suite",
    "sunny", "super", "surge", "swamp", "swarm", "swear", "sweep", "sweet",
    "swept", "swift", "swing", "swirl", "swore", "sworn", "syrup", "table",
    "taint", "taken", "taste", "teach", "tease", "teddy", "teeth", "tempo",
    "theft", "theme", "thick", "thief", "thing", "think", "third", "those",
    "three", "threw", "throw", "thumb", "tidal", "tiger", "tight", "timer",
    "tired", "titan", "title", "toast", "today", "token", "topic", "torch",
    "total", "touch", "tough", "tower", "toxic", "trace", "track", "trade",
    "trail", "train", "trait", "trash", "tread", "treat", "trend", "trial",
    "tribe", "tried", "troop", "truck", "truly", "trump", "trunk", "trust",
    "truth", "tuber", "tulip", "tumor", "tuned", "twice", "twist", "ultra",
    "under", "unity", "until", "upper", "upset", "urban", "usage", "usual",
    "utter", "valid", "value", "valve", "vapor", "vault", "verse", "video",
    "vigor", "viral", "virus", "visit", "visor", "vista", "vital", "vivid",
    "vocal", "voice", "voter", "wagon", "waist", "waste", "watch", "water",
    "weary", "weave", "wedge", "weigh", "weird", "wheat", "wheel", "where",
    "which", "while", "white", "whole", "whose", "width", "witch", "woman",
    "women", "world", "worry", "worse", "worst", "worth", "would", "wound",
    "wreck", "write", "wrong", "wrote", "yield", "young", "youth", "zebra",

    # Category 4: 6-8 letter words for additional coverage
    "absorb", "accent", "accept", "access", "across", "action", "active",
    "actual", "admire", "advice", "advise", "affair", "affect", "afford",
    "agenda", "almost", "always", "amount", "anchor", "animal", "annual",
    "anthem", "anyone", "anyway", "appeal", "appear", "archer", "arrive",
    "artist", "assure", "attack", "attend", "august", "autumn", "avatar",
    "avenue", "backup", "bakery", "ballet", "bamboo", "banana", "bandit",
    "banker", "banner", "barber", "barely", "barrel", "basket", "baxter",
    "beacon", "beauty", "become", "before", "behind", "belong", "beside",
    "better", "beyond", "blanch", "border", "bother", "bottle", "bottom",
    "bounce", "branch", "breath", "breeze", "bridge", "bright", "broken",
    "bronze", "browse", "bubble", "bucket", "budget", "buffer", "bumble",
    "bundle", "burner", "button", "bypass", "camera", "campus", "candle",
    "canvas", "canyon", "carbon", "career", "carpet", "castle", "casual",
    "caught", "caution", "center", "cereal", "chance", "change", "charge",
    "cherry", "choose", "chosen", "church", "circle", "circus", "citrus",
    "client", "closet", "clover", "cobalt", "cobble", "coffee", "colony",
    "column", "combat", "comedy", "common", "comply", "copper", "corner",
    "cotton", "couple", "course", "cousin", "cradle", "create", "credit",
    "crisis", "custom", "daemon", "damage", "dancer", "danger", "dating",
    "dealer", "debate", "decent", "decide", "defeat", "defend", "define",
    "degree", "delete", "demand", "denial", "depend", "deploy", "desert",
    "design", "desire", "detail", "detect", "device", "devote", "dialog",
    "differ", "dinner", "direct", "divide", "doctor", "domain", "donkey",
    "double", "dragon", "drawer", "driver", "during", "eleven", "emerge",
    "empire", "enable", "ending", "energy", "engage", "engine", "enough",
    "ensure", "entire", "escape", "estate", "evolve", "exceed", "except",
    "excite", "excuse", "expand", "expect", "expert", "export", "extend",
    "extent", "fabric", "factor", "falcon", "family", "famine", "famous",
    "farmer", "father", "faucet", "feather", "fellow", "female", "figure",
    "filter", "finger", "finish", "flavor", "flight", "flower", "flying",
    "follow", "forbid", "forest", "forget", "formal", "format", "former",
    "fossil", "freeze", "friend", "frozen", "fulfil", "furnace", "future",
    "galaxy", "gamble", "gaming", "garage", "garden", "garlic", "gather",
    "geared", "gender", "gentle", "geyser", "gifted", "ginger", "glacier",
    "global", "golden", "gospel", "govern", "gravel", "ground", "growth",
    "guitar", "gutter", "hammer", "handle", "happen", "harbor", "hazard",
    "health", "hereby", "hidden", "highly", "hollow", "honest", "horror",
    "hotdog", "hunger", "hunter", "hurdle", "hustle", "hybrid", "iceberg",
    "ignore", "immune", "impact", "import", "impose", "income", "indeed",
    "indoor", "infant", "inform", "injury", "insect", "inside", "insist",
    "intact", "intend", "intent", "invent", "invest", "invite", "island",
    "itself", "jacket", "jaguar", "jargon", "jersey", "jigsaw", "jogger",
    "jumble", "jungle", "junior", "keeper", "kernel", "kettle", "kidney",
    "kitten", "ladder", "lament", "laptop", "launch", "laurel", "lavish",
    "lawyer", "layout", "leader", "league", "legend", "lender", "length",
    "lesson", "letter", "likely", "linear", "liquid", "listen", "litter",
    "little", "lively", "lizard", "logger", "lonely", "lovely", "luxury",
    "magnet", "maiden", "mainly", "malice", "manage", "mangle", "manner",
    "mantle", "marble", "margin", "marine", "market", "master", "matter",
    "meadow", "medium", "member", "memory", "mental", "mentor", "merely",
    "method", "middle", "mighty", "mingle", "minute", "mirror", "misery",
    "mister", "mobile", "modern", "modest", "moment", "monkey", "mostly",
    "mother", "motion", "motive", "muscle", "museum", "mutual", "myself",
    "mystic", "napkin", "narrow", "nation", "native", "nature", "nearby",
    "nearly", "needle", "newest", "nickel", "nimble", "normal", "notice",
    "nozzle", "number", "object", "obtain", "occupy", "office", "online",
    "oppose", "option", "orange", "orchid", "origin", "outage", "outfit",
    "outlet", "output", "outrun", "oxford", "oyster", "paddle", "palace",
    "pallet", "pamper", "parade", "parcel", "parent", "parrot", "partly",
    "patron", "patter", "payday", "pebble", "pencil", "people", "pepper",
    "period", "permit", "person", "phrase", "picker", "picket", "picnic",
    "pillar", "pillow", "pirate", "planet", "plight", "plunge", "pocket",
    "poetry", "poison", "police", "polish", "polite", "pollen", "pontoon",
    "poplar", "portal", "poster", "potato", "potter", "powder", "prayer",
    "prefer", "prefix", "pretty", "priest", "prince", "prison", "profit",
    "prompt", "proper", "propel", "public", "puddle", "puppet", "purple",
    "pursue", "puzzle", "quarry", "rabbit", "racket", "radius", "ramble",
    "random", "rascal", "rather", "rattle", "reason", "recall", "recent",
    "recipe", "record", "reduce", "reform", "refund", "regard", "region",
    "reject", "relate", "relief", "remain", "remedy", "remind", "remote",
    "remove", "render", "renew", "rental", "repair", "repeat", "report",
    "rescue", "reside", "resign", "resist", "resort", "result", "retain",
    "retire", "return", "reveal", "review", "revolt", "reward", "ribbon",
    "riddle", "ripple", "ritual", "robust", "rocket", "roller", "rookie",
    "roster", "rubber", "rubble", "rumble", "runner", "rustic", "saddle",
    "safari", "safety", "sailor", "salary", "salmon", "sample", "sandal",
    "satire", "saving", "scenic", "scheme", "school", "screen", "script",
    "scroll", "search", "season", "second", "secret", "sector", "secure",
    "seldom", "select", "seller", "senior", "series", "server", "settle",
    "severe", "shadow", "shaman", "shield", "shiver", "shower", "shrink",
    "signal", "silent", "silver", "simple", "sinful", "single", "sister",
    "sketch", "slogan", "smelly", "social", "socket", "soften", "solely",
    "solemn", "source", "speech", "sphere", "spider", "spirit", "splash",
    "sponge", "spread", "spring", "square", "stable", "stream", "street",
    "stress", "strict", "stride", "strike", "string", "stripe", "stroke",
    "strong", "studio", "submit", "subtle", "sudden", "suffer", "summer",
    "summit", "supply", "surely", "survey", "switch", "symbol", "system",
    "tablet", "tackle", "tactic", "tailor", "talent", "target", "temple",
    "tenant", "tender", "tennis", "terror", "theory", "thirst", "though",
    "thread", "thrill", "thrive", "throne", "ticket", "timber", "tissue",
    "toggle", "tomato", "tongue", "toward", "travel", "treaty", "tribal",
    "trophy", "tunnel", "turtle", "twelve", "unique", "united", "unless",
    "unlock", "update", "uphold", "upload", "valley", "vanish", "vanity",
    "vendor", "vessel", "victim", "violin", "virtue", "vision", "visual",
    "vivace", "volume", "waffle", "walker", "wallet", "wander", "wanted",
    "warmth", "weapon", "weekly", "wealth", "weight", "whisky", "wicked",
    "widget", "window", "winner", "winter", "wisdom", "wonder", "wooden",
    "worker", "worthy", "writer", "yellow", "zenith", "zipper", "zodiac",

    # Category 5: Nature & Geography words (great for a location system)
    "alpine", "aurora", "basalt", "bayou", "beach", "bluff", "brook",
    "canopy", "cavern", "cliff", "coast", "coral", "cove", "creek",
    "delta", "desert", "dune", "ember", "fauna", "field", "fjord",
    "flora", "forest", "frost", "glade", "gorge", "grotto", "grove",
    "harbor", "haven", "heath", "hill", "hollow", "horizon", "island",
    "jungle", "lagoon", "lake", "marsh", "meadow", "mesa", "mist",
    "moor", "mountain", "oasis", "ocean", "orchid", "pasture", "peak",
    "plain", "plateau", "pond", "prairie", "quarry", "ravine", "reef",
    "ridge", "river", "rocky", "savanna", "shore", "sierra", "slope",
    "spring", "stream", "summit", "swamp", "thorn", "timber", "tundra",
    "valley", "volcano", "waterfall", "wetland", "wildflower",

    # Category 6: Longer descriptive words (for remote/unique areas)
    "absolute", "abundant", "acoustic", "advocate", "aircraft", "alliance",
    "altitude", "aluminum", "ambition", "ancestor", "anecdote", "anywhere",
    "appendix", "appetite", "archives", "armchair", "asteroid", "athletic",
    "aviation", "backbone", "backyard", "balanced", "barbecue", "barefoot",
    "basement", "baseball", "bathroom", "bearable", "bedrooms", "believer",
    "billowed", "birthday", "blankets", "blessing", "blizzard", "blockade",
    "blossoms", "boldness", "bookmark", "borrowed", "bouncing", "boundary",
    "brackets", "branches", "breaking", "breakers", "breeding", "burgundy",
    "backpack", "blanched", "bordered", "borrowed", "branched", "breasted",
    "calendar", "campaign", "campfire", "captured", "cardinal", "carriage",
    "carrying", "cascades", "category", "cautious", "ceremony", "champion",
    "chapters", "charcoal", "checksum", "cheerful", "chemical", "children",
    "chipmunk", "circular", "climbing", "clockwork", "clothing", "coasting",
    "cobblest", "cohesion", "collapse", "colleges", "colonial", "colorful",
    "combined", "comedian", "commonly", "communal", "compared", "compiler",
    "composed", "compound", "computer", "concepts", "concrete", "conducts",
    "confined", "conflict", "congress", "connects", "conquest", "conserve",
    "consider", "consists", "constant", "consumer", "contains", "contents",
    "continue", "contract", "contrast", "controls", "converge", "cookbook",
    "corridor", "counties", "coupling", "courtesy", "coverage", "cowardly",
    "creature", "credited", "criminal", "crossing", "crouched", "cultural",
    "currency", "customer", "cylinder", "database", "daughter", "daylight",
    "deadline", "december", "deciding", "declared", "declined", "decrease",
    "deepened", "defender", "definite", "delicate", "delivery", "demanded",
    "democrat", "departed", "depicted", "deployed", "deposits", "designer",
    "destined", "detailed", "detected", "diamonds", "dinosaur", "diplomat",
    "directed", "director", "disabled", "disagree", "discover", "discrete",
    "dispatch", "disposal", "disposed", "distance", "distinct", "district",
    "dividend", "doctrine", "document", "domestic", "dominant", "donation",
    "doubtful", "downhill", "downtown", "dramatic", "drifting", "drinking",
    "duration", "dwelling", "dynamics", "earnings", "economic", "educated",
    "effected", "eighteen", "election", "electric", "elements", "elevated",
    "elevator", "eligible", "embedded", "emigrant", "emission", "emotions",
    "emphasis", "employed", "employee", "employer", "emulated", "enclosed",
    "encoding", "enormous", "enrolled", "ensemble", "entering", "entirely",
    "entitled", "entrance", "envelope", "equipped", "escalate", "escalator",
    "essentia", "estimate", "evaluate", "eventual", "evidence", "everyday",
    "everyone", "evolving", "examined", "examiner", "examples", "exchange",
    "excluded", "executed", "exercise", "exhibits", "existing", "expanded",
    "expected", "expedite", "expenses", "expiring", "explicit", "explorer",
    "exponent", "exported", "extended", "external", "extracts", "extremes",
    "eyebrows", "fabulous", "facility", "fairness", "faithful", "falconer",
    "familiar", "farthest", "fastened", "favoring", "favorite", "featured",
    "february", "feedback", "festival", "finished", "fireside", "firmness",
    "flagship", "flamingo", "flatness", "flexible", "floating", "flooding",
    "florence", "flourish", "followed", "follower", "football", "foothold",
    "footstep", "forecast", "foremost", "forgiven", "formally", "formerly",
    "formulae", "fortress", "forwards", "founding", "fountain", "fourteen",
    "fracture", "fragment", "franklin", "freehold", "frequent", "freshest",
    "friendly", "frontier", "frosting", "fruitful", "fullness", "function",
    "fuselage", "galaxies", "gambling", "gamified", "garments", "gathered",
    "generate", "genetics", "genocide", "geometry", "gladness", "glancing",
    "glaucoma", "globally", "glorious", "glossary", "goldfish", "goodness",
    "gorgeous", "governed", "governor", "graceful", "gradient", "graduate",
    "graphics", "grateful", "gravelly", "guardian", "guidance", "gumption",
    "habitual", "hallmark", "handbook", "handmade", "happened", "hardship",
    "hardware", "harmless", "harmonic", "harshest", "headline", "hearings",
    "heavenly", "heritage", "highland", "highways", "hilarity", "historic",
    "holistic", "homeland", "homepage", "homework", "honestly", "honeybee",
    "hopeless", "hospital", "humility", "humorous", "hundreds", "huntsman",
    "hydrogen", "idealism", "illusion", "imagined", "immature", "imminent",
    "immunity", "imperial", "implicit", "imported", "imposing", "improved",
    "incident", "included", "increase", "indicate", "indirect", "indulged",
    "industry", "inferior", "infinite", "informal", "informed", "inherent",
    "initiate", "innocent", "inquired", "inscribe", "intended", "interest",
    "interior", "internal", "interval", "intimate", "invented", "inventor",
    "invested", "investor", "invoiced", "involved", "isolated", "japanese",
    "jealousy", "jettison", "judgment", "junction", "keyboard", "kindness",
    "kingdoms", "knapsack", "labeling", "landmark", "landlord", "language",
    "latitude", "launched", "lavender", "lawfully", "learning", "leftover",
    "leveling", "leverage", "liberate", "lifetime", "lighting", "likewise",
    "limiting", "listened", "literacy", "literary", "loadable", "lobbyist",
    "location", "lockdown", "logistic", "luminous", "lunchbox", "machines",
    "magnetic", "maintain", "majority", "mandated", "manifest", "mansions",
    "marathon", "marginal", "markedly", "marriage", "mastered", "material",
    "matrices", "measured", "mechanic", "medicine", "medieval", "meetings",
    "membrane", "memorial", "merchant", "metaphor", "midnight", "military",
    "minimize", "ministry", "minority", "miracles", "mistaken", "moderate",
    "modified", "moisture", "molecule", "monarchy", "monetary", "monsters",
    "monument", "moonrise", "morality", "moreover", "mortgage", "mounting",
    "movement", "multiply", "mundane", "mushroom", "mustache", "mutually",
    "mycelium", "myselfal", "mythical", "nameless", "national", "navigate",
    "necklace", "negative", "neighbor", "nestling", "networks", "newcomer",
    "nitrogen", "nameable", "nonsense", "normally", "nostrum", "notebook",
    "noteworthy", "numerous", "objected", "observed", "observer", "obtained",
    "occasion", "occupant", "occurred", "offering", "official", "offshore",
    "onscreen", "openness", "operated", "operator", "opponent", "opposite",
    "optimism", "optional", "ordering", "ordinary", "organism", "organize",
    "original", "ornament", "outbreak", "outdoors", "outlined", "outreach",
    "outsider", "overcome", "overflow", "overhead", "overlook", "overseas",
    "overtime", "overview", "owerbird", "painting", "pamphlet", "parallel",
    "parental", "partners", "passport", "password", "patience", "pavilion",
    "peaceful", "peculiar", "pedantic", "penguins", "pensions", "perceive",
    "perfecto", "periodic", "personal", "persuade", "petition", "pheasant",
    "physical", "pilaster", "pinpoint", "pipeline", "platform", "platonic",
    "plaustle", "playback", "pleasant", "pleasure", "plethora", "plotting",
    "plunging", "poignant", "polished", "policing", "politics", "populace",
    "populate", "portable", "portrait", "position", "positive", "possible",
    "powerful", "practice", "precious", "predator", "prepared", "presence",
    "preserve", "pressing", "prestige", "presumed", "pretense", "prettily",
    "prevails", "prevents", "previous", "primrose", "princess", "printing",
    "priority", "prisoner", "probable", "problems", "proceeds", "produced",
    "producer", "products", "profiles", "profound", "programs", "progress",
    "projects", "prolific", "promoted", "promptly", "properly", "property",
    "prophets", "proposal", "proposed", "prospect", "prospers", "protects",
    "proteins", "protocol", "provided", "provider", "province", "prowling",
    "prudence", "publicly", "purchase", "pursuing", "puzzling", "pyramids",
    "qualifed", "quarters", "question", "quotient", "radiance", "railroad",
    "rainfall", "randomly", "readable", "reasoned", "received", "recouped",
    "recorder", "recovery", "recycled", "redesign", "reducing", "referral",
    "referred", "reformed", "reflexes", "regional", "register", "regulate",
    "rejected", "relating", "relation", "relative", "released", "relevant",
    "reliable", "relieved", "religion", "remained", "remember", "reminded",
    "removing", "renowned", "repeated", "replaced", "replying", "reported",
    "reporter", "republic", "requests", "required", "research", "reserved",
    "resident", "resigned", "resolved", "resource", "response", "restored",
    "restrain", "retained", "retainer", "retirees", "retiring", "returned",
    "revealed", "revenues", "reversed", "reviewed", "revision", "reviving",
    "rhetoric", "rigidity", "ritualed", "riverbed", "robotics", "rollback",
    "romantic", "rooftops", "rotation", "routines", "royalist", "rubicund",
    "ruthless", "sabotage", "sacristy", "sandwich", "sanitary", "sapphire",
    "sardines", "saturday", "sausages", "scandals", "scarcely", "scenario",
    "schedule", "scholars", "scissors", "scolding", "scorched", "scramble",
    "scrutiny", "sculpted", "seaboard", "seasonal", "secluded", "secondly",
    "sections", "sediment", "selected", "semester", "sensible", "sentence",
    "separate", "sequence", "sergeant", "services", "sessions", "settling",
    "severity", "shackled", "shadowed", "shambles", "shepherd", "shipping",
    "shortage", "shoulder", "showroom", "shutting", "siblings", "sickness",
    "sidewalk", "signaled", "silently", "simplest", "simulate", "sincerely",
    "situated", "skeleton", "sketched", "skillful", "slightest", "smoothly",
    "snapshot", "snowfall", "socially", "software", "solemnly", "solidify",
    "somebody", "sometime", "somewhat", "southern", "solstice", "spacious",
    "spanning", "sparkled", "speaking", "specific", "specimen", "spectral",
    "spelling", "spending", "spillway", "spirited", "splendid", "sporting",
    "spotless", "squarely", "squirrel", "stabbing", "staffing", "stagnant",
    "staining", "standing", "standard", "standing", "starfish", "starling",
    "starting", "stations", "statutes", "steadily", "steering", "stepping",
    "sterling", "stimulus", "stocking", "stopping", "storming", "stowaway",
    "straight", "strained", "stranger", "strategy", "strength", "stressed",
    "strictly", "striking", "strongly", "struggle", "stubborn", "studying",
    "stunning", "subjects", "suburban", "suddenly", "suffered", "suffixed",
    "suffrage", "suitable", "summoned", "sunlight", "sunshine", "superb",
    "superior", "supplied", "supplier", "supports", "supposed", "suppress",
    "surfaces", "surgical", "surprise", "surround", "survival", "survived",
    "survivor", "suspects", "suspense", "sustains", "swimming", "switches",
    "symbolic", "sympathy",
]

# Offensive / problematic words to exclude
BANNED_WORDS: Set[str] = {
    # Add offensive, vulgar, or otherwise inappropriate words here
    # This is critical for a production system
    "damn", "dumb", "hell", "crap", "suck", "butt", "piss",
    "slut", "whore", "bitch",
    # Add comprehensive list in production
}

# Homophones to remove one of each pair
HOMOPHONE_PAIRS = {
    "sale": "sail", "sail": "sale",
    "meet": "meat", "meat": "meet",
    "pair": "pear", "pear": "pair",
    "bare": "bear",
    "hear": "here",
    "hole": "whole",
    "knight": "night",
    "know": "no",
    "knot": "not",
    "made": "maid",
    "mail": "male",
    "one": "won",
    "peace": "piece",
    "plain": "plane",
    "rain": "reign",
    "right": "write",
    "road": "rode",
    "role": "roll",
    "scene": "seen",
    "sea": "see",
    "some": "sum",
    "son": "sun",
    "stair": "stare",
    "steal": "steel",
    "tall": "tale",
    "there": "their",
    "threw": "through",
    "to": "too",
    "wait": "weight",
    "waste": "waist",
    "weak": "week",
    "wear": "where",
    "weather": "whether",
    "which": "witch",
    "wood": "would",
}


def is_offensive(word: str) -> bool:
    """Check if word is in the banned list."""
    return word.lower() in BANNED_WORDS


def has_homophone_conflict(word: str, existing: set) -> bool:
    """Check if a homophone of this word already exists in the wordlist."""
    pair = HOMOPHONE_PAIRS.get(word.lower())
    if pair and pair in existing:
        return True
    return False


def is_valid_word(word: str) -> bool:
    """Validate a word for inclusion in the wordlist."""
    word = word.lower().strip()
    if not word:
        return False
    if not word.isalpha():
        return False
    if len(word) < 3 or len(word) > 15:
        return False
    if is_offensive(word):
        return False
    return True


def create_wordlist(target_size: int = 40000) -> List[str]:
    """
    Create a curated, deduplicated, filtered wordlist of exactly target_size words.
    """
    seen: Set[str] = set()
    filtered: List[str] = []

    for word in BASE_WORDS:
        word = word.lower().strip()
        if word in seen:
            continue
        if not is_valid_word(word):
            continue
        if has_homophone_conflict(word, seen):
            continue
        seen.add(word)
        filtered.append(word)

    # Sort by length then alphabetically (shorter words = more common areas)
    filtered.sort(key=lambda w: (len(w), w))

    # If we don't have enough words, generate synthetic ones
    # In production, you'd source from a larger corpus
    if len(filtered) < target_size:
        prefixes = [
            "sun", "moon", "star", "wind", "rain", "snow", "fire", "ice",
            "sea", "sky", "oak", "elm", "ash", "bay", "fox", "owl",
            "hawk", "dove", "swan", "deer", "wolf", "bear", "lynx",
            "gold", "jade", "ruby", "iron", "silk", "blue", "rose",
            "sage", "mint", "pine", "fern", "moss", "reed", "vine",
            "dawn", "dusk", "glow", "haze", "mist", "peak", "vale",
            "glen", "dale", "ford", "cape", "cove", "reef", "arch",
            "gate", "path", "lane", "hill", "pond", "lake", "wood",
            "rock", "sand", "clay", "peat", "turf", "moss", "lichen",
        ]
        suffixes = [
            "fall", "rise", "glow", "song", "vale", "wind", "lake",
            "dale", "ford", "wood", "hill", "brook", "bury", "wick",
            "stone", "field", "land", "well", "born", "ward", "side",
            "croft", "shaw", "thorpe", "stead", "worth", "bridge",
            "cliff", "beach", "marsh", "ridge", "grove", "haven",
            "mead", "bloom", "spark", "frost", "dew", "morn", "eve",
            "tide", "wave", "wing", "nest", "bark", "leaf", "berry",
            "seed", "root", "stem", "brow", "edge", "bend", "loop",
        ]

        import itertools
        combos = list(itertools.product(prefixes, suffixes))
        for prefix, suffix in combos:
            if len(filtered) >= target_size:
                break
            compound = prefix + suffix
            if compound not in seen and is_valid_word(compound) and len(compound) <= 12:
                seen.add(compound)
                filtered.append(compound)

        # Still not enough? Add numbered words
        i = 0
        while len(filtered) < target_size:
            synthetic = f"grid{i:04d}"
            if synthetic not in seen:
                seen.add(synthetic)
                filtered.append(synthetic)
            i += 1

    return filtered[:target_size]


def save_wordlist(wordlist: List[str], path: str = "wordlist.json"):
    """Save wordlist to JSON file."""
    with open(path, "w", encoding="utf-8") as f:
        json.dump(wordlist, f, indent=2)
    print(f"Saved {len(wordlist)} words to {path}")
    print(f"  Shortest word: '{min(wordlist, key=len)}' ({len(min(wordlist, key=len))} chars)")
    print(f"  Longest word:  '{max(wordlist, key=len)}' ({len(max(wordlist, key=len))} chars)")
    print(f"  Addressable cells: {len(wordlist)**3:,}")


def load_wordlist(path: str = "wordlist.json") -> List[str]:
    """Load wordlist from JSON file."""
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


if __name__ == "__main__":
    print("Generating Open3Words wordlist...")
    wordlist = create_wordlist(40000)
    save_wordlist(wordlist, os.path.join(os.path.dirname(__file__), "wordlist.json"))
    print("Done!")
